name = "SimpleTN"
uuid = "ef591588-0aac-4ca2-8b87-606b3b61c00a"
authors = ["Ilia Luchnikov <luchnikovilya@gmail.com>"]
version = "0.1.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArrayInterface = "7"
LinearAlgebra = "1"
Test = "1"
